### ISSUE TITLE
How usable is this currently?

### ISSUE THREAD

**Issue by MrAwesome** [timdorr/turntable-api#1]
This looks like exactly what I'm looking for in a TT api, and the code looks pretty good from a first glance. Are you planning to keep working on this, and if so - is it working now? I'd be really happy to help out.

Also - if/when it's ready, could you publish the turntable-api package to NPM? I would love to use it!

**Comment by timdorr** [comment]
It should be fully usable. I haven't enumerated every single command and message, but I have a good amount of them covered. I've written an extremely basic bot using it and haven't had any major issues.

I haven't gotten around to publishing it, but maybe will get that done soonish.

**Comment by MrAwesome** [comment]
I went down the rabbit hole last night and plugged this in with a simple bot I'm building. Good stuff! Much easier to use than the old one. I'm working on a big PR now to add new functionality and fix a couple small bugs I had. It's still too in-flight for review yet, but here it is: https://github.com/MrAwesome/turntable-api/commit/725aa694cd53b400e709dd82252cd3f9f377733c

I'll finish cleaning that up, then put up a PR when it's cleaned up. I'll close this out now, working through it gave me a good idea of what it's capable of. Love it!
